local client = require('nota.client')

describe('client', function()
  describe('get', function()
    it('validates empty id without yielding', function()
      local response = client.get('')
      assert.is_not_nil(response)
      assert.is_not_nil(response.err)
      assert.equals(-32602, response.err.code)
      assert.equals('id is required', response.err.message)
    end)

    it('validates nil id without yielding', function()
      local response = client.get(nil)
      assert.is_not_nil(response)
      assert.equals(-32602, response.err.code)
    end)
  end)
end)
